version: "3.9"
services:
  task-management-service:
    image: splendidpdf/task-management-service:0.0.1-SNAPSHOT
    container_name: task-management-service
    depends_on:
      - rabbitmq
      - redis
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_REDIS_HOST: redis
    ports:
      - '8080:8080'
    networks:
      - splendid-pdf-network

  image-service:
    image: splendidpdf/image-service:0.0.1-SNAPSHOT
    container_name: image-service
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - '8081:8080'
    networks:
      - splendid-pdf-network

  upload-service:
    image: splendidpdf/upload-service:0.0.1-SNAPSHOT
    container_name: upload-service
    depends_on:
      - rabbitmq
    environment:
      SPRING_RABBITMQ_HOST: rabbitmq
    ports:
      - '8082:8080'
    networks:
      - splendid-pdf-network

  redis:
    image: redis:7.0.4-alpine
    container_name: redis
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - .:/data
    networks:
      - splendid-pdf-network
  rabbitmq:
    image: rabbitmq:3.10.7-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - splendid-pdf-network

networks:
  splendid-pdf-network: