server:
  error:
    include-message: always
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  metrics:
    tags:
      application: ${spring.application.name}
  server:
    port: 8001
    ssl:
      enabled: false

spring:
  application:
    name: task-management-service
  redis:
    host: 127.0.0.1
    port: 6379
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: false
          initial-interval: 1000 # ms
          max-attempts: 1
          multiplier: 1.5
          max-interval: 10000 # ms
        auto-startup: false
      direct:
        auto-startup: false
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

app:
  endpoints:
    tasks-url: public/api/v1/tasks
  mq:
    exchanges:
      tasks-exchange: exchange.tasks
    queues:
      task-status-queue: queue.task-status
      image-service-queue: queue.image-service
      document-service-queue: queue.document-service
      activity-service-queue: queue.activity-service
    routing-keys:
      image-service-key: key.tasks.image-service
      document-service-key: key.tasks.document-service
      activity-service-key: key.tasks.#
  validation:
    max-image-file-size: 10240 #Kb
    max-document-file-size: 20480 #Kb
  docs:
    title: Task Management Service
    description: Creates a taskId to track user task status
    version: 1.0.0
    server:
      url: https://splendid-pdf.ru
      description: Development server

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org: INFO


